name: Update GitHub Profile with Hashnode Posts

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 4 AM UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ“¥ Checkout Repo
        uses: actions/checkout@v4

      - name: ğŸ”¥ Cache Bun Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: ğŸš€ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: ğŸ“¦ Install Dependencies
        run: bun install --silent

      - name: ğŸ“ Update README with New Articles
        run: bun updateRSS.ts

      - name: ğŸš€ Commit and Push Changes
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'Jason Nathan'
          git config --global user.email 'jjnathanjr@gmail.com'
          git add README.md
          git commit -m "ğŸ“ Update README with new blog post" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
